"use client";
import Image from "next/image";
import "./globals.css";
import { Poppins } from "next/font/google";
import { useState } from "react";

const poppins = Poppins({
  weight: ["400", "500", "700", "900"],
  style: "normal",
  subsets: ["latin"],
});
export const metadata = {
  title: "Synagro Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="bg-slate-700">
          <a className="flex justify-center" href="/">
            <Image
              src={"/./../public/logoPoke.png"}
              alt="Picture of the author"
              width={400}
              height={400}
            />
          </a>
        </div>
        {children}
      </body>
    </html>
  );
}
